# Generated by Django 5.2.1 on 2025-06-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSequence',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('accession', models.CharField(blank=True, max_length=50, null=True)),
                ('seqtype', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.IntegerField(blank=True, null=True)),
                ('organism_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('sequence_compressed', models.BinaryField(blank=True, null=True)),
                ('processed_time', models.DateTimeField(auto_now_add=True)),
                ('other_info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingQuery',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('loading', 'Loading'), ('done', 'Done'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('queue_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['queue_time'],
            },
        ),
        migrations.CreateModel(
            name='SequencePatternSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('result', models.JSONField()),
                ('search_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_analyses', to='api.completedsequence')),
            ],
            options={
                'ordering': ['-search_at'],
            },
        ),
    ]
