# Generated by Django 5.2.1 on 2025-06-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_completedsequence_id_alter_waitingquery_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitingQuery',
        ),
        migrations.AlterField(
            model_name='completedsequence',
            name='processed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
