# Generated by Django 5.2.1 on 2025-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_waitingquery_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sequencepatternsearch',
            constraint=models.UniqueConstraint(fields=('sequence', 'pattern'), name='unique_pattern_per_sequence'),
        ),
    ]
