# Generated by Django 5.2.2 on 2025-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sequencepatternsearch_search_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencepatternsearch',
            name='others',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sequencepatternsearch',
            name='result',
            field=models.JSONField(default=dict),
        ),
    ]
